name: Render Quarto

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'      

    - name: Install Quarto CLI
      uses: quarto-dev/quarto-actions@v2
      with:
        install: true

    - name: Install R package dependencies
      run: |
        Rscript -e 'install.packages(c("readr","dplyr","tidyr"), repos="https://cloud.r-project.org")'

    - name: Render all .qmd
      run: quarto render

    - name: Commit built outputs
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update rendered outputs"
        file_pattern: |
          **/*.html
          **/_site/**
